const usersData = [
    {
        "nombre" : "Fatima",
        "apellido": "Uzcategui",
        "in": "0/0",
        "out": "0/0",
        "ext": "3305",
        "nivel": "Agente",
        "grupo": "Venezuela",
        "localizacion": "Maracaibo, Venezuela",
        "ultimoEstado": "11:00am",
        "actividadTelefono": "INUSE",
        "actividadAgente": "Disponible",
    },
    {
        "nombre" : "Agar",
        "apellido": "Perich",
        "in": "1/1",
        "out": "23/30",
        "ext": "3306",
        "nivel": "Agente",
        "grupo": "Venezuela",
        "localizacion": "Caracas, Venezuela",
        "ultimoEstado": "09:00am",
        "actividadTelefono": "ONHOLD",
        "actividadAgente": "Reunion",
    },
    {
        "nombre" : "Francisca",
        "apellido": "Paz",
        "in": "2/2",
        "out": "10/20",
        "ext": "3307",
        "nivel": "Agente",
        "grupo": "Chile",
        "localizacion": "Santiago, Chile",
        "ultimoEstado": "12:00pm",
        "actividadTelefono": "NOT INUSE",
        "actividadAgente": "Desconectado",
    },
    {
        "nombre" : "Isabel",
        "apellido": "Fernandez",
        "in": "0/0",
        "out": "10/30",
        "ext": "3308",
        "nivel": "Agente",
        "grupo": "Mexico",
        "localizacion": "Ciudad de Mexico, Mexico",
        "ultimoEstado": "02:00pm",
        "actividadTelefono": "MUTE",
        "actividadAgente": "Descanso",
    },
    {
        "nombre" : "Ignacia",
        "apellido": "Agurto",
        "in": "0/0",
        "out": "15/25",
        "ext": "3309",
        "nivel": "Agente",
        "grupo": "Chile",
        "localizacion": "Paine, Chile",
        "ultimoEstado": "10:00am",
        "actividadTelefono": "ONHOLD",
        "actividadAgente": "Reunion",
    },
    {
        "nombre" : "Jacob",
        "apellido": "Filgueira",
        "in": "2/2",
        "out": "10/15",
        "ext": "3310",
        "nivel": "Agente",
        "grupo": "Chile",
        "localizacion": "Paine, Chile",
        "ultimoEstado": "12:00pm",
        "actividadTelefono": "MUTE",
        "actividadAgente": "Descanso",
    },
    {
        "nombre" : "Jorge",
        "apellido": "Agurto",
        "in": "2/2",
        "out": "6/16",
        "ext": "3311",
        "nivel": "Agente",
        "grupo": "Chile",
        "localizacion": "Santiago, Chile",
        "ultimoEstado": "04:00pm",
        "actividadTelefono": "NOT INUSE",
        "actividadAgente": "Desconectado",
    },
    {
        "nombre" : "Yajaira",
        "apellido": "Perich",
        "in": "1/1",
        "out": "11/21",
        "ext": "3312",
        "nivel": "Agente",
        "grupo": "Venezuela",
        "localizacion": "Maracaibo, Venezuela",
        "ultimoEstado": "11:00am",
        "actividadTelefono": "ONHOLD",
        "actividadAgente": "Reunion",
    },
    {
        "nombre" : "Martin",
        "apellido": "Uzcategui",
        "in": "1/1",
        "out": "5/5",
        "ext": "3313",
        "nivel": "Agente",
        "grupo": "Venezuela",
        "localizacion": "Maracaibo, Venezuela",
        "ultimoEstado": "09:00am",
        "actividadTelefono": "INUSE",
        "actividadAgente": "Disponible",
    },
    {
        "nombre" : "Sophia",
        "apellido": "Uzcategui",
        "in": "0/0",
        "out": "31/56",
        "ext": "3314",
        "nivel": "Agente",
        "grupo": "Venezuela",
        "localizacion": "Maracaibo, Venezuela",
        "ultimoEstado": "10:00am",
        "actividadTelefono": "INUSE",
        "actividadAgente": "Disponible",
    },
    {
        "nombre" : "Maria",
        "apellido": "Filgueira",
        "in": "0/0",
        "out": "5/20",
        "ext": "3315",
        "nivel": "Agente",
        "grupo": "Venezuela",
        "localizacion": "Maracaibo, Venezuela",
        "ultimoEstado": "04:00pm",
        "actividadTelefono": "NOT INUSE",
        "actividadAgente": "Desconectado",
    },
    {
        "nombre" : "Latifa",
        "apellido": "Filgueira",
        "in": "1/1",
        "out": "15/25",
        "ext": "3316",
        "nivel": "Agente",
        "grupo": "Chile",
        "localizacion": "Santiago, Chile",
        "ultimoEstado": "03:00pm",
        "actividadTelefono": "ONHOLD",
        "actividadAgente": "Reunion",
    },
    {
        "nombre" : "Aliq",
        "apellido": "Abdellah",
        "in": "2/2",
        "out": "20/25",
        "ext": "3317",
        "nivel": "Agente",
        "grupo": "Irak",
        "localizacion": "Erbil, Irak",
        "ultimoEstado": "10:00am",
        "actividadTelefono": "INUSE",
        "actividadAgente": "Disponible",
    },
    {
        "nombre" : "Lana",
        "apellido": "Abdul Samad",
        "in": "0/0",
        "out": "10/15",
        "ext": "3318",
        "nivel": "Agente",
        "grupo": "Irak",
        "localizacion": "Basrah, Irak",
        "ultimoEstado": "10:30am",
        "actividadTelefono": "ONHOLD",
        "actividadAgente": "Reunion",
    },
    {
        "nombre" : "Jamal",
        "apellido": "Abdellah",
        "in": "1/1",
        "out": "20/25",
        "ext": "3319",
        "nivel": "Agente",
        "grupo": "Irak",
        "localizacion": "Basrah, Irak",
        "ultimoEstado": "11:30am",
        "actividadTelefono": "INUSE",
        "actividadAgente": "Disponible",
    },
    {
        "nombre" : "Aurora",
        "apellido": "Abdellah",
        "in": "2/2",
        "out": "5/10",
        "ext": "3320",
        "nivel": "Agente",
        "grupo": "Siria",
        "localizacion": "Lattakia, Siria",
        "ultimoEstado": "12:15pm",
        "actividadTelefono": "MUTE",
        "actividadAgente": "Descanso",
    },
    {
        "nombre" : "Consuelo",
        "apellido": "Abdellah",
        "in": "2/2",
        "out": "10/15",
        "ext": "3321",
        "nivel": "Agente",
        "grupo": "Siria",
        "localizacion": "Lattakia, Siria",
        "ultimoEstado": "10:25am",
        "actividadTelefono": "ONHOLD",
        "actividadAgente": "Reunion",
    },
    {
        "nombre" : "Emir",
        "apellido": "Abu Hamdi",
        "in": "1/1",
        "out": "5/25",
        "ext": "3322",
        "nivel": "Agente",
        "grupo": "Siria",
        "localizacion": "Damasco, Siria",
        "ultimoEstado": "11:15am",
        "actividadTelefono": "NOT INUSE",
        "actividadAgente": "Desconectado",
    },

]